### ISSUE TITLE
Proc-Macro crate

### ISSUE THREAD

**Issue by Mettwasser** [semantic-release-cargo/semantic-release-cargo#455]
How would you go about using it in combination with proc macros? Is there anything to watch out for/special you need to do?
For example, this project structure:
```
my_crate/
| - src/
|   | - ...
|
| - my_crate_macros/
|   | - src/
|   |   | - ...
|   |
|   | - Cargo.toml
|
| - Cargo.toml
```

**Comment by DASPRiD** [comment]
Nothing special really, it should just work. Have a look at a repo where I did that:

https://github.com/DASPRiD/jsonapi-deserialize-rs/

**Comment by EricCrosson** [comment]
Thanks for sharing @DASPRiD! 

Closing this issue for now, since there don't appear to be any action items.
