### ISSUE TITLE
Allow setting features for specific packages during publish

### ISSUE THREAD

**Issue by arlyon** [semantic-release-cargo/semantic-release-cargo#48]
Hi! I am looking to add this to async-stripe, but we require the user to pick a runtime when using the package and, by extension, require that a runtime is set during publishing or else the build will fail.

I am in the process of writing this feature, but want to open an issue to track as well.

Thanks! Alex

**Comment by EricCrosson** [comment]
Hey there @arlyon,

how are you thinking of controlling this feature? Is it something to be expressed as a native `semantic-release` configuration, like:

```json
[
  "@semantic-release-cargo/semantic-release-cargo",
  {
    "features": ["feat-1", "feat-2"]
  }
]
```
?

**Comment by arlyon** [comment]
Probably one step up, actually:

```json
[
  "@semantic-release-cargo/semantic-release-cargo",
  {
    "features": {
      "my_package": ["feat-1", "feat-2"]
    }
  }
]
```

Seems like napi-rs is capable of parsing that into a `Hashmap<String, Vec<String>>` out of the box.
